ansible_connection: network_cli
ansible_network_os: ios
ansible_user: admin
ansible_ssh_pass: "{{ vault_password }}"
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: "{{ vault_password }}"