- hosts: localhost
  gather_facts: false

  vars:
    - IP: 172.31.3.13/23
    - IPADDRESS: 172.31.3.1
    - MASK: 255.255.255.128
    - CIDR: 192.168.0.0/16
    - MAC: 1a:2b:3c:4d:5e:6f
    - PREFIX: 18
  ##   network {{ vlan.network }} {{ (vlan.network+'/'+vlan.mask)|ipaddr('wildcard') }}
  tasks:
    - debug: msg="___ {{ MASK }} ___ ADDRESS {{ (IPADDRESS+'/'+MASK)|ipaddr('wildcard') }}"
    - debug: msg="___ {{ IP }} ___ ADDRESS {{ IP | ipaddr('address') }}"
    #- debug: msg="___ {{ IP }} ___ BROADCAST {{ IP | ipaddr('broadcast') }}"
    #- debug: msg="___ {{ IP }} ___ NETMASK {{ IP | ipaddr('netmask') }}"
    - debug: msg="___ {{ IP }} ___ NETWORK {{ IP | ipaddr('network') }}"
    #- debug: msg="___ {{ IP }} ___ PREFIX {{ IP | ipaddr('prefix') }}"
    #- debug: msg="___ {{ IP }} ___ SIZE {{ IP | ipaddr('size') }}"
    #- debug: msg="___ {{ IP }} ___ WILDCARD {{ IP | ipaddr('wildcard') }}"
    #- debug: msg="___ {{ IP }} ___ RANGE {{ IP | ipaddr('range_usable') }}"
    #- debug: msg="___ {{ IP }} ___ REVERSE DNS {{ IP | ipaddr('revdns') }}"
    #- debug: msg="___ {{ IP }} ___ HEX {{ IP | ipaddr('address') | ip4_hex() }}"
    #- debug: msg="___ {{ MAC }} ___ CISCO {{ MAC | hwaddr('cisco') }}"
    #- debug: msg="___ {{ CIDR }} ___ Last /20 CIDR {{ CIDR | ipsubnet(20, -1) }}"
    #- debug: msg="___ {{ CIDR }} ___ 1st IP {{ CIDR | ipaddr(1) }}"
    #- debug: msg="___ {{ CIDR }} ___ 3rd from last IP {{ CIDR | ipaddr(-3) }}"
