- name: build template
  template:
    src: address_famely.j2
    dest: "output/{{ inventory_hostname  }}.txt"

- name: build template for tunnels
  template:
    src: address_famely_tunnel.j2
    dest: "output/{{ inventory_hostname  }}_tunnel.txt"
